### ISSUE TITLE
Invalid library found in C:\Users\UserName\Documents\Arduino\libraries\NintendoSwitchControlLibrary-master: Missing 'paragraph' from library

### ISSUE THREAD

**Issue by ktysne** [lefmarna/NintendoSwitchControlLibrary#18]
下記の記事を参照して環境構築を進めています。
https://pokemonit.com/micon-introduction/

Arduino IDEの下記バージョンのWindows版、Mac版の両方を試して全てにおいて同じエラーが表示されます。
* 2.0.0
* 1.8.19
* 1.8.13

## 環境
* Windows 10 (21H2)
* macOS Monterey (12.5.1)

## 手順
1. 記事のスクショにバージョンを合わせるため```1.8.13```を[公式サイト](https://www.arduino.cc/en/software/OldSoftwareReleases)からダウンロード & インストール
2. ```Arduino AVR Boards```の```1.8.3```をインストール
3. [Github](https://github.com/lefmarna/NintendoSwitchControlLibrary)の```Code```から```Download ZIP```を選択
4. Zipファイルを展開して```NintendoSwitchControlLibrary-master```を```libraries```にコピー
5. 題名のエラーが表示される
※日本語環境の場合は下記の表記となる。
```
「C:\Users\UserName\Documents\Arduino\libraries\NintendoSwitchControlLibrary-master」に、無効なライブラリ「Missing 'paragraph' from library」があります。
```

**Comment by lefmarna** [comment]
報告ありがとうございます！

WindowsとMac両方で再現するとのことでバージョン情報も含め詳細とても助かります。

こちらでは再現できていないので原因についてはわかりかねるのですが、エラー文言を見るに`library.properties`に`paragraph`が用意されていないことが問題なのかなと推測してまして、早速これを用意した`v1.3.1`をリリースいたしました！

ダウンロード先: https://github.com/lefmarna/NintendoSwitchControlLibrary/releases/tag/v1.3.1

修正内容: https://github.com/lefmarna/NintendoSwitchControlLibrary/pull/19/commits/c0345695a079b2d90113b783552394ad92aa0b59

よろしければ、最新の`v1.3.1`でもエラーが出るかどうかを試していただきたいです。

なお、Arduino IDEの2.0.0はサポートできていないため、1.8.*のもので確認いただければと思います。

**Comment by ktysne** [comment]
@lefmarna 
お忙しい中、素早い対応ありがとうございました。
ご対応いただいた```v1.3.1```にて正常にコンパイル・書き込みを完了する事ができました。
