### ISSUE TITLE
SVでの卵管理

### ISSUE THREAD

**Issue by okuRaku** [lefmarna/NintendoSwitchControlLibrary#22]
どうもはじめまして。

SVの金策で、ボタンをひたすら押すターボ機能が常識だと思いますが、手持ちにArduboyがありましてので、うまくプログラムできないかなと思いまして、運よく本ライブラリを見つけました。ArduinoIDE内の機能で発見しました。ご説明の文もわかりやすくて、数分で動けるようになりました！感謝満々で幸いです。

さて、こんなに簡単に自動化出来ちゃうのだったら卵からの色違いを狙うのも手の届く範囲に？と思って、exampleで付属して頂いた剣盾版（孵化）を参考に、作ってみようと思ったんですが、もしかして、作者様も既に作っていらっしゃいますか？　とお尋ねしたくてIssueを作ってみました。

本ライブラリ、ドキュメントの作成ありがとうございます！すごく役に立ちそうです。

**Comment by lefmarna** [comment]
はじめまして！ お役に立てたようで嬉しいです。

正直なところ、SVは自動化が難しいです。ですが、完全なものではないものの孵化のコードを作ることはできました。日本語のブログなのですが、以下のページ内にコードを貼っております。

https://pokemonit.com/sv-hatch-eggs-in-the-box/

今回のコードではタマゴを孵化するのみで受け取るのはやっていないのですが、それも近いうちにやりたいですね！

**Comment by okuRaku** [comment]
返事ありがとうございます！

わぁ～すごい！是非参考にしてみます！どうもありがとうございます！

では、このissueは閉じさせていただきますね。勝手な要望ですみませんでした！

楽しみがまた増えました＾＾
